version: '3.7'
services:
  app:
    build:
      context: .
    container_name: ${CONTAINER_NAME} 
    image: cards_game
    restart: always
    volumes:
      - "./react-app/public:/app/public"
      - "./react-app/src:/app/src"
    command: npm start
    
    ports:
      - ${APP_PORT}:3000

    environment:
      - NODE_ENV=development
